server:
  port: 8881
spring:
  application:
    name: provider-server-01
eureka:
  instance:
    hostname: 127.0.0.1
    lease-expiration-duration-in-seconds: 9
    lease-renewal-interval-in-seconds: 3
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server-01:8888/eureka/,http://eureka-server-02:8088/eureka/,http://eureka-server-03:8008/eureka/

